# array reshape

### 1d to 2d

In [2]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(len(x))
newarr = x.reshape(4, 3)

print(newarr)

12
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [2]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = x.reshape(3, 4)

print(newarr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [3]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = x.reshape(6, 2)

print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [4]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = x.reshape(2, 6)

print(newarr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


### 1-D to 3-D

In [3]:

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = x.reshape(3, 2, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [5]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = x.reshape(3, 2, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [1]:
import numpy as np

arr = np.array([1, 2, 3])

for i in arr:
  print(i)

1
2
3


In [5]:
l=[[1,2,3],[3,4,5]]
for i in l:
    for j in i:
        print(j)

1
2
3
3
4
5


In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [8]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [9]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [6]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [13]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [11]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [12]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [14]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [10]:

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.Collecting opencv-python
   ---------------------------------------- 0.0/40.2 MB ? eta -:--:--
   - -------------------------------------- 1.5/40.2 MB 30.9 MB/s eta 0:00:02
   --- ------------------------------------ 3.5/40.2 MB 36.7 MB/s eta 0:00:02
   ----- ---------------------------------- 5.4/40.2 MB 38.2 MB/s eta 0:00:01
   ------- -------------------------------- 7.8/40.2 MB 41.3 MB/s eta 0:00:01
   ---------- ----------------------------- 10.1/40.2 MB 43.0 MB/s eta 0:00:01
   ------------ --------------------------- 12.4/40.2 MB 46.9 MB/s eta 0:00:01
   ------------- -------------------------- 13.8/40.2 MB 50.4 MB/s eta 0:00:01
   --------------- ------------------------ 15.1/40.2 MB 43.7 MB/s eta 0:00:01
   ----------------- ---------------------- 17.2/40.2 MB 43.7 MB/s eta 0:00:01
   ------------------ --------------------- 19.0/40.2 MB 43.5 MB/s eta 0:00:01
   --------------------- ------------------ 21.2/40.2 

  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
contourpy 1.2.0 requires numpy<2.0,>=1.20, but you have numpy 2.4.3 which is incompatible.
numba 0.61.2 requires numpy<2.3,>=1.24, but you have numpy 2.4.3 which is incompatible.
pywavelets 1.5.0 requires numpy<2.0,>=1.22.4, but you have numpy 2.4.3 which is incompatible.
scipy 1.13.1 requires numpy<2.3,>=1.22.4, but you have numpy 2.4.3 which is incompatible.


In [ ]:
import numpy as np
img = np.xeros
((5,5,3), dtype = np = uint8