In [2]:
import numpy as np

In [6]:
array = [1,2,3,4,5,6,7,8,9]


In [7]:
print(array)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [8]:
print(type(array))

<class 'list'>


In [11]:
array = array*2
print(array)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [12]:
array = np.array(array)
print(array)

[1 2 3 4 5 6 7 8 9 1 2 3 4 5 6 7 8 9]


In [13]:
print(type(array))

<class 'numpy.ndarray'>


In [14]:
array = array*2
print(array)

[ 2  4  6  8 10 12 14 16 18  2  4  6  8 10 12 14 16 18]


In [23]:
arr = np.array([1,5,9,8,7,4,5,6,3,2,1,4,7,11,55,41,21,23], dtype = np.int8)


In [20]:
print( arr + array)

[ 3  9 15 16 17 16 19 22 21  4  5 10 15 21 67 55 37 41]


In [24]:
print(arr.dtype)

int8
